#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: fae1327
#
Name     : compat-taglib-soname1
Version  : 1.13.1
Release  : 14
URL      : https://taglib.org/releases/taglib-1.13.1.tar.gz
Source0  : https://taglib.org/releases/taglib-1.13.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 MPL-1.1
Requires: compat-taglib-soname1-lib = %{version}-%{release}
Requires: compat-taglib-soname1-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
There are a few other people that have done bindings externally that I have
been made aware of.  I have not personally reviewed these bindings, but I'm
listing them here so that those who find them useful are able to find them:

%package lib
Summary: lib components for the compat-taglib-soname1 package.
Group: Libraries
Requires: compat-taglib-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-taglib-soname1 package.


%package license
Summary: license components for the compat-taglib-soname1 package.
Group: Default

%description license
license components for the compat-taglib-soname1 package.


%prep
%setup -q -n taglib-1.13.1
cd %{_builddir}/taglib-1.13.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706121270
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706121270
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-taglib-soname1
cp %{_builddir}/taglib-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/compat-taglib-soname1/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/taglib-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/compat-taglib-soname1/aba8d76d0af67d57da3c3c321caa59f3d242386b || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/bin/taglib-config
rm -f %{buildroot}*/usr/include/taglib/aifffile.h
rm -f %{buildroot}*/usr/include/taglib/aiffproperties.h
rm -f %{buildroot}*/usr/include/taglib/apefile.h
rm -f %{buildroot}*/usr/include/taglib/apefooter.h
rm -f %{buildroot}*/usr/include/taglib/apeitem.h
rm -f %{buildroot}*/usr/include/taglib/apeproperties.h
rm -f %{buildroot}*/usr/include/taglib/apetag.h
rm -f %{buildroot}*/usr/include/taglib/asfattribute.h
rm -f %{buildroot}*/usr/include/taglib/asffile.h
rm -f %{buildroot}*/usr/include/taglib/asfpicture.h
rm -f %{buildroot}*/usr/include/taglib/asfproperties.h
rm -f %{buildroot}*/usr/include/taglib/asftag.h
rm -f %{buildroot}*/usr/include/taglib/attachedpictureframe.h
rm -f %{buildroot}*/usr/include/taglib/audioproperties.h
rm -f %{buildroot}*/usr/include/taglib/chapterframe.h
rm -f %{buildroot}*/usr/include/taglib/commentsframe.h
rm -f %{buildroot}*/usr/include/taglib/eventtimingcodesframe.h
rm -f %{buildroot}*/usr/include/taglib/fileref.h
rm -f %{buildroot}*/usr/include/taglib/flacfile.h
rm -f %{buildroot}*/usr/include/taglib/flacmetadatablock.h
rm -f %{buildroot}*/usr/include/taglib/flacpicture.h
rm -f %{buildroot}*/usr/include/taglib/flacproperties.h
rm -f %{buildroot}*/usr/include/taglib/generalencapsulatedobjectframe.h
rm -f %{buildroot}*/usr/include/taglib/id3v1genres.h
rm -f %{buildroot}*/usr/include/taglib/id3v1tag.h
rm -f %{buildroot}*/usr/include/taglib/id3v2.h
rm -f %{buildroot}*/usr/include/taglib/id3v2extendedheader.h
rm -f %{buildroot}*/usr/include/taglib/id3v2footer.h
rm -f %{buildroot}*/usr/include/taglib/id3v2frame.h
rm -f %{buildroot}*/usr/include/taglib/id3v2framefactory.h
rm -f %{buildroot}*/usr/include/taglib/id3v2header.h
rm -f %{buildroot}*/usr/include/taglib/id3v2synchdata.h
rm -f %{buildroot}*/usr/include/taglib/id3v2tag.h
rm -f %{buildroot}*/usr/include/taglib/infotag.h
rm -f %{buildroot}*/usr/include/taglib/itfile.h
rm -f %{buildroot}*/usr/include/taglib/itproperties.h
rm -f %{buildroot}*/usr/include/taglib/modfile.h
rm -f %{buildroot}*/usr/include/taglib/modfilebase.h
rm -f %{buildroot}*/usr/include/taglib/modproperties.h
rm -f %{buildroot}*/usr/include/taglib/modtag.h
rm -f %{buildroot}*/usr/include/taglib/mp4atom.h
rm -f %{buildroot}*/usr/include/taglib/mp4coverart.h
rm -f %{buildroot}*/usr/include/taglib/mp4file.h
rm -f %{buildroot}*/usr/include/taglib/mp4item.h
rm -f %{buildroot}*/usr/include/taglib/mp4properties.h
rm -f %{buildroot}*/usr/include/taglib/mp4tag.h
rm -f %{buildroot}*/usr/include/taglib/mpcfile.h
rm -f %{buildroot}*/usr/include/taglib/mpcproperties.h
rm -f %{buildroot}*/usr/include/taglib/mpegfile.h
rm -f %{buildroot}*/usr/include/taglib/mpegheader.h
rm -f %{buildroot}*/usr/include/taglib/mpegproperties.h
rm -f %{buildroot}*/usr/include/taglib/oggfile.h
rm -f %{buildroot}*/usr/include/taglib/oggflacfile.h
rm -f %{buildroot}*/usr/include/taglib/oggpage.h
rm -f %{buildroot}*/usr/include/taglib/oggpageheader.h
rm -f %{buildroot}*/usr/include/taglib/opusfile.h
rm -f %{buildroot}*/usr/include/taglib/opusproperties.h
rm -f %{buildroot}*/usr/include/taglib/ownershipframe.h
rm -f %{buildroot}*/usr/include/taglib/podcastframe.h
rm -f %{buildroot}*/usr/include/taglib/popularimeterframe.h
rm -f %{buildroot}*/usr/include/taglib/privateframe.h
rm -f %{buildroot}*/usr/include/taglib/relativevolumeframe.h
rm -f %{buildroot}*/usr/include/taglib/rifffile.h
rm -f %{buildroot}*/usr/include/taglib/s3mfile.h
rm -f %{buildroot}*/usr/include/taglib/s3mproperties.h
rm -f %{buildroot}*/usr/include/taglib/speexfile.h
rm -f %{buildroot}*/usr/include/taglib/speexproperties.h
rm -f %{buildroot}*/usr/include/taglib/synchronizedlyricsframe.h
rm -f %{buildroot}*/usr/include/taglib/tableofcontentsframe.h
rm -f %{buildroot}*/usr/include/taglib/tag.h
rm -f %{buildroot}*/usr/include/taglib/tag_c.h
rm -f %{buildroot}*/usr/include/taglib/taglib.h
rm -f %{buildroot}*/usr/include/taglib/taglib_config.h
rm -f %{buildroot}*/usr/include/taglib/taglib_export.h
rm -f %{buildroot}*/usr/include/taglib/tbytevector.h
rm -f %{buildroot}*/usr/include/taglib/tbytevectorlist.h
rm -f %{buildroot}*/usr/include/taglib/tbytevectorstream.h
rm -f %{buildroot}*/usr/include/taglib/tdebuglistener.h
rm -f %{buildroot}*/usr/include/taglib/textidentificationframe.h
rm -f %{buildroot}*/usr/include/taglib/tfile.h
rm -f %{buildroot}*/usr/include/taglib/tfilestream.h
rm -f %{buildroot}*/usr/include/taglib/tiostream.h
rm -f %{buildroot}*/usr/include/taglib/tlist.h
rm -f %{buildroot}*/usr/include/taglib/tlist.tcc
rm -f %{buildroot}*/usr/include/taglib/tmap.h
rm -f %{buildroot}*/usr/include/taglib/tmap.tcc
rm -f %{buildroot}*/usr/include/taglib/tpropertymap.h
rm -f %{buildroot}*/usr/include/taglib/trefcounter.h
rm -f %{buildroot}*/usr/include/taglib/trueaudiofile.h
rm -f %{buildroot}*/usr/include/taglib/trueaudioproperties.h
rm -f %{buildroot}*/usr/include/taglib/tstring.h
rm -f %{buildroot}*/usr/include/taglib/tstringlist.h
rm -f %{buildroot}*/usr/include/taglib/uniquefileidentifierframe.h
rm -f %{buildroot}*/usr/include/taglib/unknownframe.h
rm -f %{buildroot}*/usr/include/taglib/unsynchronizedlyricsframe.h
rm -f %{buildroot}*/usr/include/taglib/urllinkframe.h
rm -f %{buildroot}*/usr/include/taglib/vorbisfile.h
rm -f %{buildroot}*/usr/include/taglib/vorbisproperties.h
rm -f %{buildroot}*/usr/include/taglib/wavfile.h
rm -f %{buildroot}*/usr/include/taglib/wavpackfile.h
rm -f %{buildroot}*/usr/include/taglib/wavpackproperties.h
rm -f %{buildroot}*/usr/include/taglib/wavproperties.h
rm -f %{buildroot}*/usr/include/taglib/xingheader.h
rm -f %{buildroot}*/usr/include/taglib/xiphcomment.h
rm -f %{buildroot}*/usr/include/taglib/xmfile.h
rm -f %{buildroot}*/usr/include/taglib/xmproperties.h
rm -f %{buildroot}*/usr/lib64/libtag.so
rm -f %{buildroot}*/usr/lib64/libtag_c.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/taglib.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/taglib_c.pc
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libtag.so.1.19.1
/V3/usr/lib64/libtag_c.so.0.0.0
/usr/lib64/libtag.so.1
/usr/lib64/libtag.so.1.19.1
/usr/lib64/libtag_c.so.0
/usr/lib64/libtag_c.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-taglib-soname1/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/compat-taglib-soname1/aba8d76d0af67d57da3c3c321caa59f3d242386b
